// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: clouddrive.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CloudDriveFileSrv_GetToken_FullMethodName           = "/clouddrive.CloudDriveFileSrv/GetToken"
	CloudDriveFileSrv_GetSubFiles_FullMethodName        = "/clouddrive.CloudDriveFileSrv/GetSubFiles"
	CloudDriveFileSrv_FindFileByPath_FullMethodName     = "/clouddrive.CloudDriveFileSrv/FindFileByPath"
	CloudDriveFileSrv_CreateFolder_FullMethodName       = "/clouddrive.CloudDriveFileSrv/CreateFolder"
	CloudDriveFileSrv_RenameFile_FullMethodName         = "/clouddrive.CloudDriveFileSrv/RenameFile"
	CloudDriveFileSrv_MoveFile_FullMethodName           = "/clouddrive.CloudDriveFileSrv/MoveFile"
	CloudDriveFileSrv_CopyFile_FullMethodName           = "/clouddrive.CloudDriveFileSrv/CopyFile"
	CloudDriveFileSrv_DeleteFile_FullMethodName         = "/clouddrive.CloudDriveFileSrv/DeleteFile"
	CloudDriveFileSrv_GetSpaceInfo_FullMethodName       = "/clouddrive.CloudDriveFileSrv/GetSpaceInfo"
	CloudDriveFileSrv_CreateFile_FullMethodName         = "/clouddrive.CloudDriveFileSrv/CreateFile"
	CloudDriveFileSrv_CloseFile_FullMethodName          = "/clouddrive.CloudDriveFileSrv/CloseFile"
	CloudDriveFileSrv_WriteToFile_FullMethodName        = "/clouddrive.CloudDriveFileSrv/WriteToFile"
	CloudDriveFileSrv_GetDownloadUrlPath_FullMethodName = "/clouddrive.CloudDriveFileSrv/GetDownloadUrlPath"
)

// CloudDriveFileSrvClient is the client API for CloudDriveFileSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CloudDriveFileSrv is the subset of the published CloudDrive2 gRPC
// service used by this backend. Field numbers match
// https://www.clouddrive2.com/api/clouddrive.proto
type CloudDriveFileSrvClient interface {
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*JWTToken, error)
	GetSubFiles(ctx context.Context, in *ListSubFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubFilesReply], error)
	FindFileByPath(ctx context.Context, in *FindFileByPathRequest, opts ...grpc.CallOption) (*CloudDriveFile, error)
	CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*CreateFolderResult, error)
	RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*FileOperationResult, error)
	MoveFile(ctx context.Context, in *MoveFileRequest, opts ...grpc.CallOption) (*FileOperationResult, error)
	CopyFile(ctx context.Context, in *CopyFileRequest, opts ...grpc.CallOption) (*FileOperationResult, error)
	DeleteFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileOperationResult, error)
	GetSpaceInfo(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*SpaceInfo, error)
	CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*CreateFileResult, error)
	CloseFile(ctx context.Context, in *CloseFileRequest, opts ...grpc.CallOption) (*FileOperationResult, error)
	WriteToFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResult, error)
	GetDownloadUrlPath(ctx context.Context, in *GetDownloadUrlPathRequest, opts ...grpc.CallOption) (*DownloadUrlPathInfo, error)
}

type cloudDriveFileSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudDriveFileSrvClient(cc grpc.ClientConnInterface) CloudDriveFileSrvClient {
	return &cloudDriveFileSrvClient{cc}
}

func (c *cloudDriveFileSrvClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*JWTToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JWTToken)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_GetToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) GetSubFiles(ctx context.Context, in *ListSubFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubFilesReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CloudDriveFileSrv_ServiceDesc.Streams[0], CloudDriveFileSrv_GetSubFiles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListSubFileRequest, SubFilesReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CloudDriveFileSrv_GetSubFilesClient = grpc.ServerStreamingClient[SubFilesReply]

func (c *cloudDriveFileSrvClient) FindFileByPath(ctx context.Context, in *FindFileByPathRequest, opts ...grpc.CallOption) (*CloudDriveFile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloudDriveFile)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_FindFileByPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*CreateFolderResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFolderResult)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_CreateFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*FileOperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileOperationResult)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_RenameFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) MoveFile(ctx context.Context, in *MoveFileRequest, opts ...grpc.CallOption) (*FileOperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileOperationResult)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_MoveFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) CopyFile(ctx context.Context, in *CopyFileRequest, opts ...grpc.CallOption) (*FileOperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileOperationResult)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_CopyFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) DeleteFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileOperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileOperationResult)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) GetSpaceInfo(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*SpaceInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpaceInfo)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_GetSpaceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*CreateFileResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFileResult)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_CreateFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) CloseFile(ctx context.Context, in *CloseFileRequest, opts ...grpc.CallOption) (*FileOperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileOperationResult)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_CloseFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) WriteToFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResult)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_WriteToFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudDriveFileSrvClient) GetDownloadUrlPath(ctx context.Context, in *GetDownloadUrlPathRequest, opts ...grpc.CallOption) (*DownloadUrlPathInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadUrlPathInfo)
	err := c.cc.Invoke(ctx, CloudDriveFileSrv_GetDownloadUrlPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudDriveFileSrvServer is the server API for CloudDriveFileSrv service.
// All implementations must embed UnimplementedCloudDriveFileSrvServer
// for forward compatibility.
//
// CloudDriveFileSrv is the subset of the published CloudDrive2 gRPC
// service used by this backend. Field numbers match
// https://www.clouddrive2.com/api/clouddrive.proto
type CloudDriveFileSrvServer interface {
	GetToken(context.Context, *GetTokenRequest) (*JWTToken, error)
	GetSubFiles(*ListSubFileRequest, grpc.ServerStreamingServer[SubFilesReply]) error
	FindFileByPath(context.Context, *FindFileByPathRequest) (*CloudDriveFile, error)
	CreateFolder(context.Context, *CreateFolderRequest) (*CreateFolderResult, error)
	RenameFile(context.Context, *RenameFileRequest) (*FileOperationResult, error)
	MoveFile(context.Context, *MoveFileRequest) (*FileOperationResult, error)
	CopyFile(context.Context, *CopyFileRequest) (*FileOperationResult, error)
	DeleteFile(context.Context, *FileRequest) (*FileOperationResult, error)
	GetSpaceInfo(context.Context, *FileRequest) (*SpaceInfo, error)
	CreateFile(context.Context, *CreateFileRequest) (*CreateFileResult, error)
	CloseFile(context.Context, *CloseFileRequest) (*FileOperationResult, error)
	WriteToFile(context.Context, *WriteFileRequest) (*WriteFileResult, error)
	GetDownloadUrlPath(context.Context, *GetDownloadUrlPathRequest) (*DownloadUrlPathInfo, error)
	mustEmbedUnimplementedCloudDriveFileSrvServer()
}

// UnimplementedCloudDriveFileSrvServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCloudDriveFileSrvServer struct{}

func (UnimplementedCloudDriveFileSrvServer) GetToken(context.Context, *GetTokenRequest) (*JWTToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) GetSubFiles(*ListSubFileRequest, grpc.ServerStreamingServer[SubFilesReply]) error {
	return status.Errorf(codes.Unimplemented, "method GetSubFiles not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) FindFileByPath(context.Context, *FindFileByPathRequest) (*CloudDriveFile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindFileByPath not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) CreateFolder(context.Context, *CreateFolderRequest) (*CreateFolderResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFolder not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) RenameFile(context.Context, *RenameFileRequest) (*FileOperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameFile not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) MoveFile(context.Context, *MoveFileRequest) (*FileOperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveFile not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) CopyFile(context.Context, *CopyFileRequest) (*FileOperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopyFile not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) DeleteFile(context.Context, *FileRequest) (*FileOperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) GetSpaceInfo(context.Context, *FileRequest) (*SpaceInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpaceInfo not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) CreateFile(context.Context, *CreateFileRequest) (*CreateFileResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFile not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) CloseFile(context.Context, *CloseFileRequest) (*FileOperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseFile not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) WriteToFile(context.Context, *WriteFileRequest) (*WriteFileResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteToFile not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) GetDownloadUrlPath(context.Context, *GetDownloadUrlPathRequest) (*DownloadUrlPathInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDownloadUrlPath not implemented")
}
func (UnimplementedCloudDriveFileSrvServer) mustEmbedUnimplementedCloudDriveFileSrvServer() {}
func (UnimplementedCloudDriveFileSrvServer) testEmbeddedByValue()                           {}

// UnsafeCloudDriveFileSrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudDriveFileSrvServer will
// result in compilation errors.
type UnsafeCloudDriveFileSrvServer interface {
	mustEmbedUnimplementedCloudDriveFileSrvServer()
}

func RegisterCloudDriveFileSrvServer(s grpc.ServiceRegistrar, srv CloudDriveFileSrvServer) {
	// If the following call pancis, it indicates UnimplementedCloudDriveFileSrvServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CloudDriveFileSrv_ServiceDesc, srv)
}

func _CloudDriveFileSrv_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_GetToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_GetSubFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListSubFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CloudDriveFileSrvServer).GetSubFiles(m, &grpc.GenericServerStream[ListSubFileRequest, SubFilesReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CloudDriveFileSrv_GetSubFilesServer = grpc.ServerStreamingServer[SubFilesReply]

func _CloudDriveFileSrv_FindFileByPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindFileByPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).FindFileByPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_FindFileByPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).FindFileByPath(ctx, req.(*FindFileByPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_CreateFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).CreateFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_CreateFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).CreateFolder(ctx, req.(*CreateFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_RenameFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).RenameFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_RenameFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).RenameFile(ctx, req.(*RenameFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_MoveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).MoveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_MoveFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).MoveFile(ctx, req.(*MoveFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_CopyFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).CopyFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_CopyFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).CopyFile(ctx, req.(*CopyFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).DeleteFile(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_GetSpaceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).GetSpaceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_GetSpaceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).GetSpaceInfo(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_CreateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).CreateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_CreateFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).CreateFile(ctx, req.(*CreateFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_CloseFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).CloseFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_CloseFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).CloseFile(ctx, req.(*CloseFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_WriteToFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).WriteToFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_WriteToFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).WriteToFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudDriveFileSrv_GetDownloadUrlPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDownloadUrlPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudDriveFileSrvServer).GetDownloadUrlPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudDriveFileSrv_GetDownloadUrlPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudDriveFileSrvServer).GetDownloadUrlPath(ctx, req.(*GetDownloadUrlPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudDriveFileSrv_ServiceDesc is the grpc.ServiceDesc for CloudDriveFileSrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudDriveFileSrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clouddrive.CloudDriveFileSrv",
	HandlerType: (*CloudDriveFileSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToken",
			Handler:    _CloudDriveFileSrv_GetToken_Handler,
		},
		{
			MethodName: "FindFileByPath",
			Handler:    _CloudDriveFileSrv_FindFileByPath_Handler,
		},
		{
			MethodName: "CreateFolder",
			Handler:    _CloudDriveFileSrv_CreateFolder_Handler,
		},
		{
			MethodName: "RenameFile",
			Handler:    _CloudDriveFileSrv_RenameFile_Handler,
		},
		{
			MethodName: "MoveFile",
			Handler:    _CloudDriveFileSrv_MoveFile_Handler,
		},
		{
			MethodName: "CopyFile",
			Handler:    _CloudDriveFileSrv_CopyFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _CloudDriveFileSrv_DeleteFile_Handler,
		},
		{
			MethodName: "GetSpaceInfo",
			Handler:    _CloudDriveFileSrv_GetSpaceInfo_Handler,
		},
		{
			MethodName: "CreateFile",
			Handler:    _CloudDriveFileSrv_CreateFile_Handler,
		},
		{
			MethodName: "CloseFile",
			Handler:    _CloudDriveFileSrv_CloseFile_Handler,
		},
		{
			MethodName: "WriteToFile",
			Handler:    _CloudDriveFileSrv_WriteToFile_Handler,
		},
		{
			MethodName: "GetDownloadUrlPath",
			Handler:    _CloudDriveFileSrv_GetDownloadUrlPath_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSubFiles",
			Handler:       _CloudDriveFileSrv_GetSubFiles_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "clouddrive.proto",
}
