// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: clouddrive.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoveFileRequest_ConflictPolicy int32

const (
	MoveFileRequest_Overwrite MoveFileRequest_ConflictPolicy = 0
	MoveFileRequest_Rename    MoveFileRequest_ConflictPolicy = 1
	MoveFileRequest_Skip      MoveFileRequest_ConflictPolicy = 2
)

// Enum value maps for MoveFileRequest_ConflictPolicy.
var (
	MoveFileRequest_ConflictPolicy_name = map[int32]string{
		0: "Overwrite",
		1: "Rename",
		2: "Skip",
	}
	MoveFileRequest_ConflictPolicy_value = map[string]int32{
		"Overwrite": 0,
		"Rename":    1,
		"Skip":      2,
	}
)

func (x MoveFileRequest_ConflictPolicy) Enum() *MoveFileRequest_ConflictPolicy {
	p := new(MoveFileRequest_ConflictPolicy)
	*p = x
	return p
}

func (x MoveFileRequest_ConflictPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MoveFileRequest_ConflictPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_clouddrive_proto_enumTypes[0].Descriptor()
}

func (MoveFileRequest_ConflictPolicy) Type() protoreflect.EnumType {
	return &file_clouddrive_proto_enumTypes[0]
}

func (x MoveFileRequest_ConflictPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MoveFileRequest_ConflictPolicy.Descriptor instead.
func (MoveFileRequest_ConflictPolicy) EnumDescriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{14, 0}
}

type CloudDriveFile_FileType int32

const (
	CloudDriveFile_Directory CloudDriveFile_FileType = 0
	CloudDriveFile_File      CloudDriveFile_FileType = 1
	CloudDriveFile_Other     CloudDriveFile_FileType = 2
)

// Enum value maps for CloudDriveFile_FileType.
var (
	CloudDriveFile_FileType_name = map[int32]string{
		0: "Directory",
		1: "File",
		2: "Other",
	}
	CloudDriveFile_FileType_value = map[string]int32{
		"Directory": 0,
		"File":      1,
		"Other":     2,
	}
)

func (x CloudDriveFile_FileType) Enum() *CloudDriveFile_FileType {
	p := new(CloudDriveFile_FileType)
	*p = x
	return p
}

func (x CloudDriveFile_FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloudDriveFile_FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_clouddrive_proto_enumTypes[1].Descriptor()
}

func (CloudDriveFile_FileType) Type() protoreflect.EnumType {
	return &file_clouddrive_proto_enumTypes[1]
}

func (x CloudDriveFile_FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloudDriveFile_FileType.Descriptor instead.
func (CloudDriveFile_FileType) EnumDescriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{19, 0}
}

type GetTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	TotpCode      *string                `protobuf:"bytes,3,opt,name=totpCode,proto3,oneof" json:"totpCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_clouddrive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{0}
}

func (x *GetTokenRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GetTokenRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetTokenRequest) GetTotpCode() string {
	if x != nil && x.TotpCode != nil {
		return *x.TotpCode
	}
	return ""
}

type JWTToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Expiration    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTToken) Reset() {
	*x = JWTToken{}
	mi := &file_clouddrive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTToken) ProtoMessage() {}

func (x *JWTToken) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTToken.ProtoReflect.Descriptor instead.
func (*JWTToken) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{1}
}

func (x *JWTToken) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JWTToken) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JWTToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JWTToken) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ForceRefresh  *bool                  `protobuf:"varint,2,opt,name=forceRefresh,proto3,oneof" json:"forceRefresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_clouddrive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{2}
}

func (x *FileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileRequest) GetForceRefresh() bool {
	if x != nil && x.ForceRefresh != nil {
		return *x.ForceRefresh
	}
	return false
}

type FileOperationResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	ResultFilePaths []string               `protobuf:"bytes,3,rep,name=resultFilePaths,proto3" json:"resultFilePaths,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileOperationResult) Reset() {
	*x = FileOperationResult{}
	mi := &file_clouddrive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOperationResult) ProtoMessage() {}

func (x *FileOperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOperationResult.ProtoReflect.Descriptor instead.
func (*FileOperationResult) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{3}
}

func (x *FileOperationResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileOperationResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *FileOperationResult) GetResultFilePaths() []string {
	if x != nil {
		return x.ResultFilePaths
	}
	return nil
}

type GetDownloadUrlPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Preview       bool                   `protobuf:"varint,2,opt,name=preview,proto3" json:"preview,omitempty"`
	LazyRead      bool                   `protobuf:"varint,3,opt,name=lazy_read,json=lazyRead,proto3" json:"lazy_read,omitempty"`
	GetDirectUrl  bool                   `protobuf:"varint,4,opt,name=get_direct_url,json=getDirectUrl,proto3" json:"get_direct_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlPathRequest) Reset() {
	*x = GetDownloadUrlPathRequest{}
	mi := &file_clouddrive_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlPathRequest) ProtoMessage() {}

func (x *GetDownloadUrlPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlPathRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlPathRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{4}
}

func (x *GetDownloadUrlPathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetDownloadUrlPathRequest) GetPreview() bool {
	if x != nil {
		return x.Preview
	}
	return false
}

func (x *GetDownloadUrlPathRequest) GetLazyRead() bool {
	if x != nil {
		return x.LazyRead
	}
	return false
}

func (x *GetDownloadUrlPathRequest) GetGetDirectUrl() bool {
	if x != nil {
		return x.GetDirectUrl
	}
	return false
}

type DownloadUrlPathInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrlPath   string                 `protobuf:"bytes,1,opt,name=downloadUrlPath,proto3" json:"downloadUrlPath,omitempty"`
	ExpiresIn         *uint64                `protobuf:"varint,2,opt,name=expiresIn,proto3,oneof" json:"expiresIn,omitempty"`
	DirectUrl         *string                `protobuf:"bytes,3,opt,name=directUrl,proto3,oneof" json:"directUrl,omitempty"`
	UserAgent         *string                `protobuf:"bytes,4,opt,name=userAgent,proto3,oneof" json:"userAgent,omitempty"`
	AdditionalHeaders map[string]string      `protobuf:"bytes,5,rep,name=additionalHeaders,proto3" json:"additionalHeaders,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DownloadUrlPathInfo) Reset() {
	*x = DownloadUrlPathInfo{}
	mi := &file_clouddrive_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadUrlPathInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadUrlPathInfo) ProtoMessage() {}

func (x *DownloadUrlPathInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadUrlPathInfo.ProtoReflect.Descriptor instead.
func (*DownloadUrlPathInfo) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadUrlPathInfo) GetDownloadUrlPath() string {
	if x != nil {
		return x.DownloadUrlPath
	}
	return ""
}

func (x *DownloadUrlPathInfo) GetExpiresIn() uint64 {
	if x != nil && x.ExpiresIn != nil {
		return *x.ExpiresIn
	}
	return 0
}

func (x *DownloadUrlPathInfo) GetDirectUrl() string {
	if x != nil && x.DirectUrl != nil {
		return *x.DirectUrl
	}
	return ""
}

func (x *DownloadUrlPathInfo) GetUserAgent() string {
	if x != nil && x.UserAgent != nil {
		return *x.UserAgent
	}
	return ""
}

func (x *DownloadUrlPathInfo) GetAdditionalHeaders() map[string]string {
	if x != nil {
		return x.AdditionalHeaders
	}
	return nil
}

type ListSubFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ForceRefresh  bool                   `protobuf:"varint,2,opt,name=forceRefresh,proto3" json:"forceRefresh,omitempty"`
	CheckExpires  *bool                  `protobuf:"varint,3,opt,name=checkExpires,proto3,oneof" json:"checkExpires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubFileRequest) Reset() {
	*x = ListSubFileRequest{}
	mi := &file_clouddrive_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubFileRequest) ProtoMessage() {}

func (x *ListSubFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubFileRequest.ProtoReflect.Descriptor instead.
func (*ListSubFileRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{6}
}

func (x *ListSubFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListSubFileRequest) GetForceRefresh() bool {
	if x != nil {
		return x.ForceRefresh
	}
	return false
}

func (x *ListSubFileRequest) GetCheckExpires() bool {
	if x != nil && x.CheckExpires != nil {
		return *x.CheckExpires
	}
	return false
}

type SubFilesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubFiles      []*CloudDriveFile      `protobuf:"bytes,1,rep,name=subFiles,proto3" json:"subFiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubFilesReply) Reset() {
	*x = SubFilesReply{}
	mi := &file_clouddrive_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubFilesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubFilesReply) ProtoMessage() {}

func (x *SubFilesReply) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubFilesReply.ProtoReflect.Descriptor instead.
func (*SubFilesReply) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{7}
}

func (x *SubFilesReply) GetSubFiles() []*CloudDriveFile {
	if x != nil {
		return x.SubFiles
	}
	return nil
}

type FindFileByPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentPath    string                 `protobuf:"bytes,1,opt,name=parentPath,proto3" json:"parentPath,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindFileByPathRequest) Reset() {
	*x = FindFileByPathRequest{}
	mi := &file_clouddrive_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindFileByPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindFileByPathRequest) ProtoMessage() {}

func (x *FindFileByPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindFileByPathRequest.ProtoReflect.Descriptor instead.
func (*FindFileByPathRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{8}
}

func (x *FindFileByPathRequest) GetParentPath() string {
	if x != nil {
		return x.ParentPath
	}
	return ""
}

func (x *FindFileByPathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CreateFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentPath    string                 `protobuf:"bytes,1,opt,name=parentPath,proto3" json:"parentPath,omitempty"`
	FolderName    string                 `protobuf:"bytes,2,opt,name=folderName,proto3" json:"folderName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderRequest) Reset() {
	*x = CreateFolderRequest{}
	mi := &file_clouddrive_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderRequest) ProtoMessage() {}

func (x *CreateFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderRequest.ProtoReflect.Descriptor instead.
func (*CreateFolderRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{9}
}

func (x *CreateFolderRequest) GetParentPath() string {
	if x != nil {
		return x.ParentPath
	}
	return ""
}

func (x *CreateFolderRequest) GetFolderName() string {
	if x != nil {
		return x.FolderName
	}
	return ""
}

type CreateFolderResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderCreated *CloudDriveFile        `protobuf:"bytes,1,opt,name=folderCreated,proto3" json:"folderCreated,omitempty"`
	Result        *FileOperationResult   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderResult) Reset() {
	*x = CreateFolderResult{}
	mi := &file_clouddrive_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderResult) ProtoMessage() {}

func (x *CreateFolderResult) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderResult.ProtoReflect.Descriptor instead.
func (*CreateFolderResult) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{10}
}

func (x *CreateFolderResult) GetFolderCreated() *CloudDriveFile {
	if x != nil {
		return x.FolderCreated
	}
	return nil
}

func (x *CreateFolderResult) GetResult() *FileOperationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type CreateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentPath    string                 `protobuf:"bytes,1,opt,name=parentPath,proto3" json:"parentPath,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileRequest) Reset() {
	*x = CreateFileRequest{}
	mi := &file_clouddrive_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequest) ProtoMessage() {}

func (x *CreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequest.ProtoReflect.Descriptor instead.
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{11}
}

func (x *CreateFileRequest) GetParentPath() string {
	if x != nil {
		return x.ParentPath
	}
	return ""
}

func (x *CreateFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type CreateFileResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileHandle    uint64                 `protobuf:"varint,1,opt,name=fileHandle,proto3" json:"fileHandle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileResult) Reset() {
	*x = CreateFileResult{}
	mi := &file_clouddrive_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResult) ProtoMessage() {}

func (x *CreateFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResult.ProtoReflect.Descriptor instead.
func (*CreateFileResult) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{12}
}

func (x *CreateFileResult) GetFileHandle() uint64 {
	if x != nil {
		return x.FileHandle
	}
	return 0
}

type CloseFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileHandle    uint64                 `protobuf:"varint,1,opt,name=fileHandle,proto3" json:"fileHandle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseFileRequest) Reset() {
	*x = CloseFileRequest{}
	mi := &file_clouddrive_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseFileRequest) ProtoMessage() {}

func (x *CloseFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseFileRequest.ProtoReflect.Descriptor instead.
func (*CloseFileRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{13}
}

func (x *CloseFileRequest) GetFileHandle() uint64 {
	if x != nil {
		return x.FileHandle
	}
	return 0
}

type MoveFileRequest struct {
	state          protoimpl.MessageState          `protogen:"open.v1"`
	TheFilePaths   []string                        `protobuf:"bytes,1,rep,name=theFilePaths,proto3" json:"theFilePaths,omitempty"`
	DestPath       string                          `protobuf:"bytes,2,opt,name=destPath,proto3" json:"destPath,omitempty"`
	ConflictPolicy *MoveFileRequest_ConflictPolicy `protobuf:"varint,3,opt,name=conflictPolicy,proto3,enum=clouddrive.MoveFileRequest_ConflictPolicy,oneof" json:"conflictPolicy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MoveFileRequest) Reset() {
	*x = MoveFileRequest{}
	mi := &file_clouddrive_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveFileRequest) ProtoMessage() {}

func (x *MoveFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveFileRequest.ProtoReflect.Descriptor instead.
func (*MoveFileRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{14}
}

func (x *MoveFileRequest) GetTheFilePaths() []string {
	if x != nil {
		return x.TheFilePaths
	}
	return nil
}

func (x *MoveFileRequest) GetDestPath() string {
	if x != nil {
		return x.DestPath
	}
	return ""
}

func (x *MoveFileRequest) GetConflictPolicy() MoveFileRequest_ConflictPolicy {
	if x != nil && x.ConflictPolicy != nil {
		return *x.ConflictPolicy
	}
	return MoveFileRequest_Overwrite
}

type CopyFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TheFilePaths  []string               `protobuf:"bytes,1,rep,name=theFilePaths,proto3" json:"theFilePaths,omitempty"`
	DestPath      string                 `protobuf:"bytes,2,opt,name=destPath,proto3" json:"destPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFileRequest) Reset() {
	*x = CopyFileRequest{}
	mi := &file_clouddrive_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFileRequest) ProtoMessage() {}

func (x *CopyFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFileRequest.ProtoReflect.Descriptor instead.
func (*CopyFileRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{15}
}

func (x *CopyFileRequest) GetTheFilePaths() []string {
	if x != nil {
		return x.TheFilePaths
	}
	return nil
}

func (x *CopyFileRequest) GetDestPath() string {
	if x != nil {
		return x.DestPath
	}
	return ""
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileHandle    uint64                 `protobuf:"varint,1,opt,name=fileHandle,proto3" json:"fileHandle,omitempty"`
	StartPos      uint64                 `protobuf:"varint,2,opt,name=startPos,proto3" json:"startPos,omitempty"`
	Length        uint64                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	Buffer        []byte                 `protobuf:"bytes,4,opt,name=buffer,proto3" json:"buffer,omitempty"`
	CloseFile     bool                   `protobuf:"varint,5,opt,name=closeFile,proto3" json:"closeFile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_clouddrive_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{16}
}

func (x *WriteFileRequest) GetFileHandle() uint64 {
	if x != nil {
		return x.FileHandle
	}
	return 0
}

func (x *WriteFileRequest) GetStartPos() uint64 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *WriteFileRequest) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *WriteFileRequest) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

func (x *WriteFileRequest) GetCloseFile() bool {
	if x != nil {
		return x.CloseFile
	}
	return false
}

type WriteFileResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  uint64                 `protobuf:"varint,1,opt,name=bytesWritten,proto3" json:"bytesWritten,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResult) Reset() {
	*x = WriteFileResult{}
	mi := &file_clouddrive_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResult) ProtoMessage() {}

func (x *WriteFileResult) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResult.ProtoReflect.Descriptor instead.
func (*WriteFileResult) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{17}
}

func (x *WriteFileResult) GetBytesWritten() uint64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type RenameFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TheFilePath   string                 `protobuf:"bytes,1,opt,name=theFilePath,proto3" json:"theFilePath,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=newName,proto3" json:"newName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFileRequest) Reset() {
	*x = RenameFileRequest{}
	mi := &file_clouddrive_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFileRequest) ProtoMessage() {}

func (x *RenameFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFileRequest.ProtoReflect.Descriptor instead.
func (*RenameFileRequest) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{18}
}

func (x *RenameFileRequest) GetTheFilePath() string {
	if x != nil {
		return x.TheFilePath
	}
	return ""
}

func (x *RenameFileRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type CloudDriveFile struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Id              string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FullPathName    string                  `protobuf:"bytes,3,opt,name=fullPathName,proto3" json:"fullPathName,omitempty"`
	Size            int64                   `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	FileType        CloudDriveFile_FileType `protobuf:"varint,5,opt,name=fileType,proto3,enum=clouddrive.CloudDriveFile_FileType" json:"fileType,omitempty"`
	CreateTime      *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	WriteTime       *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=writeTime,proto3" json:"writeTime,omitempty"`
	AccessTime      *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=accessTime,proto3" json:"accessTime,omitempty"`
	ThumbnailUrl    string                  `protobuf:"bytes,10,opt,name=thumbnailUrl,proto3" json:"thumbnailUrl,omitempty"`
	PreviewUrl      string                  `protobuf:"bytes,11,opt,name=previewUrl,proto3" json:"previewUrl,omitempty"`
	OriginalPath    string                  `protobuf:"bytes,14,opt,name=originalPath,proto3" json:"originalPath,omitempty"`
	IsDirectory     bool                    `protobuf:"varint,30,opt,name=isDirectory,proto3" json:"isDirectory,omitempty"`
	FileHashes      map[uint32]string       `protobuf:"bytes,70,rep,name=fileHashes,proto3" json:"fileHashes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DownloadUrlPath *DownloadUrlPathInfo    `protobuf:"bytes,76,opt,name=downloadUrlPath,proto3,oneof" json:"downloadUrlPath,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CloudDriveFile) Reset() {
	*x = CloudDriveFile{}
	mi := &file_clouddrive_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudDriveFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudDriveFile) ProtoMessage() {}

func (x *CloudDriveFile) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudDriveFile.ProtoReflect.Descriptor instead.
func (*CloudDriveFile) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{19}
}

func (x *CloudDriveFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CloudDriveFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CloudDriveFile) GetFullPathName() string {
	if x != nil {
		return x.FullPathName
	}
	return ""
}

func (x *CloudDriveFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CloudDriveFile) GetFileType() CloudDriveFile_FileType {
	if x != nil {
		return x.FileType
	}
	return CloudDriveFile_Directory
}

func (x *CloudDriveFile) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *CloudDriveFile) GetWriteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.WriteTime
	}
	return nil
}

func (x *CloudDriveFile) GetAccessTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessTime
	}
	return nil
}

func (x *CloudDriveFile) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *CloudDriveFile) GetPreviewUrl() string {
	if x != nil {
		return x.PreviewUrl
	}
	return ""
}

func (x *CloudDriveFile) GetOriginalPath() string {
	if x != nil {
		return x.OriginalPath
	}
	return ""
}

func (x *CloudDriveFile) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *CloudDriveFile) GetFileHashes() map[uint32]string {
	if x != nil {
		return x.FileHashes
	}
	return nil
}

func (x *CloudDriveFile) GetDownloadUrlPath() *DownloadUrlPathInfo {
	if x != nil {
		return x.DownloadUrlPath
	}
	return nil
}

type SpaceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalSpace    int64                  `protobuf:"varint,1,opt,name=totalSpace,proto3" json:"totalSpace,omitempty"`
	UsedSpace     int64                  `protobuf:"varint,2,opt,name=usedSpace,proto3" json:"usedSpace,omitempty"`
	FreeSpace     int64                  `protobuf:"varint,3,opt,name=freeSpace,proto3" json:"freeSpace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceInfo) Reset() {
	*x = SpaceInfo{}
	mi := &file_clouddrive_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceInfo) ProtoMessage() {}

func (x *SpaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clouddrive_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceInfo.ProtoReflect.Descriptor instead.
func (*SpaceInfo) Descriptor() ([]byte, []int) {
	return file_clouddrive_proto_rawDescGZIP(), []int{20}
}

func (x *SpaceInfo) GetTotalSpace() int64 {
	if x != nil {
		return x.TotalSpace
	}
	return 0
}

func (x *SpaceInfo) GetUsedSpace() int64 {
	if x != nil {
		return x.UsedSpace
	}
	return 0
}

func (x *SpaceInfo) GetFreeSpace() int64 {
	if x != nil {
		return x.FreeSpace
	}
	return 0
}

var File_clouddrive_proto protoreflect.FileDescriptor

const file_clouddrive_proto_rawDesc = "" +
	"\n" +
	"\x10clouddrive.proto\x12\n" +
	"clouddrive\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n" +
	"\x0fGetTokenRequest\x12\x1a\n" +
	"\buserName\x18\x01 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1f\n" +
	"\btotpCode\x18\x03 \x01(\tH\x00R\btotpCode\x88\x01\x01B\v\n" +
	"\t_totpCode\"\x9a\x01\n" +
	"\bJWTToken\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\ferrorMessage\x18\x02 \x01(\tR\ferrorMessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12:\n" +
	"\n" +
	"expiration\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\"[\n" +
	"\vFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12'\n" +
	"\fforceRefresh\x18\x02 \x01(\bH\x00R\fforceRefresh\x88\x01\x01B\x0f\n" +
	"\r_forceRefresh\"}\n" +
	"\x13FileOperationResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\ferrorMessage\x18\x02 \x01(\tR\ferrorMessage\x12(\n" +
	"\x0fresultFilePaths\x18\x03 \x03(\tR\x0fresultFilePaths\"\x8c\x01\n" +
	"\x19GetDownloadUrlPathRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\apreview\x18\x02 \x01(\bR\apreview\x12\x1b\n" +
	"\tlazy_read\x18\x03 \x01(\bR\blazyRead\x12$\n" +
	"\x0eget_direct_url\x18\x04 \x01(\bR\fgetDirectUrl\"\xfe\x02\n" +
	"\x13DownloadUrlPathInfo\x12(\n" +
	"\x0fdownloadUrlPath\x18\x01 \x01(\tR\x0fdownloadUrlPath\x12!\n" +
	"\texpiresIn\x18\x02 \x01(\x04H\x00R\texpiresIn\x88\x01\x01\x12!\n" +
	"\tdirectUrl\x18\x03 \x01(\tH\x01R\tdirectUrl\x88\x01\x01\x12!\n" +
	"\tuserAgent\x18\x04 \x01(\tH\x02R\tuserAgent\x88\x01\x01\x12d\n" +
	"\x11additionalHeaders\x18\x05 \x03(\v26.clouddrive.DownloadUrlPathInfo.AdditionalHeadersEntryR\x11additionalHeaders\x1aD\n" +
	"\x16AdditionalHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_expiresInB\f\n" +
	"\n" +
	"_directUrlB\f\n" +
	"\n" +
	"_userAgent\"\x86\x01\n" +
	"\x12ListSubFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\"\n" +
	"\fforceRefresh\x18\x02 \x01(\bR\fforceRefresh\x12'\n" +
	"\fcheckExpires\x18\x03 \x01(\bH\x00R\fcheckExpires\x88\x01\x01B\x0f\n" +
	"\r_checkExpires\"G\n" +
	"\rSubFilesReply\x126\n" +
	"\bsubFiles\x18\x01 \x03(\v2\x1a.clouddrive.CloudDriveFileR\bsubFiles\"K\n" +
	"\x15FindFileByPathRequest\x12\x1e\n" +
	"\n" +
	"parentPath\x18\x01 \x01(\tR\n" +
	"parentPath\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"U\n" +
	"\x13CreateFolderRequest\x12\x1e\n" +
	"\n" +
	"parentPath\x18\x01 \x01(\tR\n" +
	"parentPath\x12\x1e\n" +
	"\n" +
	"folderName\x18\x02 \x01(\tR\n" +
	"folderName\"\x8f\x01\n" +
	"\x12CreateFolderResult\x12@\n" +
	"\rfolderCreated\x18\x01 \x01(\v2\x1a.clouddrive.CloudDriveFileR\rfolderCreated\x127\n" +
	"\x06result\x18\x02 \x01(\v2\x1f.clouddrive.FileOperationResultR\x06result\"O\n" +
	"\x11CreateFileRequest\x12\x1e\n" +
	"\n" +
	"parentPath\x18\x01 \x01(\tR\n" +
	"parentPath\x12\x1a\n" +
	"\bfileName\x18\x02 \x01(\tR\bfileName\"2\n" +
	"\x10CreateFileResult\x12\x1e\n" +
	"\n" +
	"fileHandle\x18\x01 \x01(\x04R\n" +
	"fileHandle\"2\n" +
	"\x10CloseFileRequest\x12\x1e\n" +
	"\n" +
	"fileHandle\x18\x01 \x01(\x04R\n" +
	"fileHandle\"\xf4\x01\n" +
	"\x0fMoveFileRequest\x12\"\n" +
	"\ftheFilePaths\x18\x01 \x03(\tR\ftheFilePaths\x12\x1a\n" +
	"\bdestPath\x18\x02 \x01(\tR\bdestPath\x12W\n" +
	"\x0econflictPolicy\x18\x03 \x01(\x0e2*.clouddrive.MoveFileRequest.ConflictPolicyH\x00R\x0econflictPolicy\x88\x01\x01\"5\n" +
	"\x0eConflictPolicy\x12\r\n" +
	"\tOverwrite\x10\x00\x12\n" +
	"\n" +
	"\x06Rename\x10\x01\x12\b\n" +
	"\x04Skip\x10\x02B\x11\n" +
	"\x0f_conflictPolicy\"Q\n" +
	"\x0fCopyFileRequest\x12\"\n" +
	"\ftheFilePaths\x18\x01 \x03(\tR\ftheFilePaths\x12\x1a\n" +
	"\bdestPath\x18\x02 \x01(\tR\bdestPath\"\x9c\x01\n" +
	"\x10WriteFileRequest\x12\x1e\n" +
	"\n" +
	"fileHandle\x18\x01 \x01(\x04R\n" +
	"fileHandle\x12\x1a\n" +
	"\bstartPos\x18\x02 \x01(\x04R\bstartPos\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\x12\x16\n" +
	"\x06buffer\x18\x04 \x01(\fR\x06buffer\x12\x1c\n" +
	"\tcloseFile\x18\x05 \x01(\bR\tcloseFile\"5\n" +
	"\x0fWriteFileResult\x12\"\n" +
	"\fbytesWritten\x18\x01 \x01(\x04R\fbytesWritten\"O\n" +
	"\x11RenameFileRequest\x12 \n" +
	"\vtheFilePath\x18\x01 \x01(\tR\vtheFilePath\x12\x18\n" +
	"\anewName\x18\x02 \x01(\tR\anewName\"\x88\x06\n" +
	"\x0eCloudDriveFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\ffullPathName\x18\x03 \x01(\tR\ffullPathName\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12?\n" +
	"\bfileType\x18\x05 \x01(\x0e2#.clouddrive.CloudDriveFile.FileTypeR\bfileType\x12:\n" +
	"\n" +
	"createTime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x128\n" +
	"\twriteTime\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\twriteTime\x12:\n" +
	"\n" +
	"accessTime\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"accessTime\x12\"\n" +
	"\fthumbnailUrl\x18\n" +
	" \x01(\tR\fthumbnailUrl\x12\x1e\n" +
	"\n" +
	"previewUrl\x18\v \x01(\tR\n" +
	"previewUrl\x12\"\n" +
	"\foriginalPath\x18\x0e \x01(\tR\foriginalPath\x12 \n" +
	"\visDirectory\x18\x1e \x01(\bR\visDirectory\x12J\n" +
	"\n" +
	"fileHashes\x18F \x03(\v2*.clouddrive.CloudDriveFile.FileHashesEntryR\n" +
	"fileHashes\x12N\n" +
	"\x0fdownloadUrlPath\x18L \x01(\v2\x1f.clouddrive.DownloadUrlPathInfoH\x00R\x0fdownloadUrlPath\x88\x01\x01\x1a=\n" +
	"\x0fFileHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\bFileType\x12\r\n" +
	"\tDirectory\x10\x00\x12\b\n" +
	"\x04File\x10\x01\x12\t\n" +
	"\x05Other\x10\x02B\x12\n" +
	"\x10_downloadUrlPath\"g\n" +
	"\tSpaceInfo\x12\x1e\n" +
	"\n" +
	"totalSpace\x18\x01 \x01(\x03R\n" +
	"totalSpace\x12\x1c\n" +
	"\tusedSpace\x18\x02 \x01(\x03R\tusedSpace\x12\x1c\n" +
	"\tfreeSpace\x18\x03 \x01(\x03R\tfreeSpace2\xe9\a\n" +
	"\x11CloudDriveFileSrv\x12=\n" +
	"\bGetToken\x12\x1b.clouddrive.GetTokenRequest\x1a\x14.clouddrive.JWTToken\x12J\n" +
	"\vGetSubFiles\x12\x1e.clouddrive.ListSubFileRequest\x1a\x19.clouddrive.SubFilesReply0\x01\x12O\n" +
	"\x0eFindFileByPath\x12!.clouddrive.FindFileByPathRequest\x1a\x1a.clouddrive.CloudDriveFile\x12O\n" +
	"\fCreateFolder\x12\x1f.clouddrive.CreateFolderRequest\x1a\x1e.clouddrive.CreateFolderResult\x12L\n" +
	"\n" +
	"RenameFile\x12\x1d.clouddrive.RenameFileRequest\x1a\x1f.clouddrive.FileOperationResult\x12H\n" +
	"\bMoveFile\x12\x1b.clouddrive.MoveFileRequest\x1a\x1f.clouddrive.FileOperationResult\x12H\n" +
	"\bCopyFile\x12\x1b.clouddrive.CopyFileRequest\x1a\x1f.clouddrive.FileOperationResult\x12F\n" +
	"\n" +
	"DeleteFile\x12\x17.clouddrive.FileRequest\x1a\x1f.clouddrive.FileOperationResult\x12>\n" +
	"\fGetSpaceInfo\x12\x17.clouddrive.FileRequest\x1a\x15.clouddrive.SpaceInfo\x12I\n" +
	"\n" +
	"CreateFile\x12\x1d.clouddrive.CreateFileRequest\x1a\x1c.clouddrive.CreateFileResult\x12J\n" +
	"\tCloseFile\x12\x1c.clouddrive.CloseFileRequest\x1a\x1f.clouddrive.FileOperationResult\x12H\n" +
	"\vWriteToFile\x12\x1c.clouddrive.WriteFileRequest\x1a\x1b.clouddrive.WriteFileResult\x12\\\n" +
	"\x12GetDownloadUrlPath\x12%.clouddrive.GetDownloadUrlPathRequest\x1a\x1f.clouddrive.DownloadUrlPathInfoB2Z0github.com/rclone/rclone/backend/clouddrive2/apib\x06proto3"

var (
	file_clouddrive_proto_rawDescOnce sync.Once
	file_clouddrive_proto_rawDescData []byte
)

func file_clouddrive_proto_rawDescGZIP() []byte {
	file_clouddrive_proto_rawDescOnce.Do(func() {
		file_clouddrive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clouddrive_proto_rawDesc), len(file_clouddrive_proto_rawDesc)))
	})
	return file_clouddrive_proto_rawDescData
}

var file_clouddrive_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_clouddrive_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_clouddrive_proto_goTypes = []any{
	(MoveFileRequest_ConflictPolicy)(0), // 0: clouddrive.MoveFileRequest.ConflictPolicy
	(CloudDriveFile_FileType)(0),        // 1: clouddrive.CloudDriveFile.FileType
	(*GetTokenRequest)(nil),             // 2: clouddrive.GetTokenRequest
	(*JWTToken)(nil),                    // 3: clouddrive.JWTToken
	(*FileRequest)(nil),                 // 4: clouddrive.FileRequest
	(*FileOperationResult)(nil),         // 5: clouddrive.FileOperationResult
	(*GetDownloadUrlPathRequest)(nil),   // 6: clouddrive.GetDownloadUrlPathRequest
	(*DownloadUrlPathInfo)(nil),         // 7: clouddrive.DownloadUrlPathInfo
	(*ListSubFileRequest)(nil),          // 8: clouddrive.ListSubFileRequest
	(*SubFilesReply)(nil),               // 9: clouddrive.SubFilesReply
	(*FindFileByPathRequest)(nil),       // 10: clouddrive.FindFileByPathRequest
	(*CreateFolderRequest)(nil),         // 11: clouddrive.CreateFolderRequest
	(*CreateFolderResult)(nil),          // 12: clouddrive.CreateFolderResult
	(*CreateFileRequest)(nil),           // 13: clouddrive.CreateFileRequest
	(*CreateFileResult)(nil),            // 14: clouddrive.CreateFileResult
	(*CloseFileRequest)(nil),            // 15: clouddrive.CloseFileRequest
	(*MoveFileRequest)(nil),             // 16: clouddrive.MoveFileRequest
	(*CopyFileRequest)(nil),             // 17: clouddrive.CopyFileRequest
	(*WriteFileRequest)(nil),            // 18: clouddrive.WriteFileRequest
	(*WriteFileResult)(nil),             // 19: clouddrive.WriteFileResult
	(*RenameFileRequest)(nil),           // 20: clouddrive.RenameFileRequest
	(*CloudDriveFile)(nil),              // 21: clouddrive.CloudDriveFile
	(*SpaceInfo)(nil),                   // 22: clouddrive.SpaceInfo
	nil,                                 // 23: clouddrive.DownloadUrlPathInfo.AdditionalHeadersEntry
	nil,                                 // 24: clouddrive.CloudDriveFile.FileHashesEntry
	(*timestamppb.Timestamp)(nil),       // 25: google.protobuf.Timestamp
}
var file_clouddrive_proto_depIdxs = []int32{
	25, // 0: clouddrive.JWTToken.expiration:type_name -> google.protobuf.Timestamp
	23, // 1: clouddrive.DownloadUrlPathInfo.additionalHeaders:type_name -> clouddrive.DownloadUrlPathInfo.AdditionalHeadersEntry
	21, // 2: clouddrive.SubFilesReply.subFiles:type_name -> clouddrive.CloudDriveFile
	21, // 3: clouddrive.CreateFolderResult.folderCreated:type_name -> clouddrive.CloudDriveFile
	5,  // 4: clouddrive.CreateFolderResult.result:type_name -> clouddrive.FileOperationResult
	0,  // 5: clouddrive.MoveFileRequest.conflictPolicy:type_name -> clouddrive.MoveFileRequest.ConflictPolicy
	1,  // 6: clouddrive.CloudDriveFile.fileType:type_name -> clouddrive.CloudDriveFile.FileType
	25, // 7: clouddrive.CloudDriveFile.createTime:type_name -> google.protobuf.Timestamp
	25, // 8: clouddrive.CloudDriveFile.writeTime:type_name -> google.protobuf.Timestamp
	25, // 9: clouddrive.CloudDriveFile.accessTime:type_name -> google.protobuf.Timestamp
	24, // 10: clouddrive.CloudDriveFile.fileHashes:type_name -> clouddrive.CloudDriveFile.FileHashesEntry
	7,  // 11: clouddrive.CloudDriveFile.downloadUrlPath:type_name -> clouddrive.DownloadUrlPathInfo
	2,  // 12: clouddrive.CloudDriveFileSrv.GetToken:input_type -> clouddrive.GetTokenRequest
	8,  // 13: clouddrive.CloudDriveFileSrv.GetSubFiles:input_type -> clouddrive.ListSubFileRequest
	10, // 14: clouddrive.CloudDriveFileSrv.FindFileByPath:input_type -> clouddrive.FindFileByPathRequest
	11, // 15: clouddrive.CloudDriveFileSrv.CreateFolder:input_type -> clouddrive.CreateFolderRequest
	20, // 16: clouddrive.CloudDriveFileSrv.RenameFile:input_type -> clouddrive.RenameFileRequest
	16, // 17: clouddrive.CloudDriveFileSrv.MoveFile:input_type -> clouddrive.MoveFileRequest
	17, // 18: clouddrive.CloudDriveFileSrv.CopyFile:input_type -> clouddrive.CopyFileRequest
	4,  // 19: clouddrive.CloudDriveFileSrv.DeleteFile:input_type -> clouddrive.FileRequest
	4,  // 20: clouddrive.CloudDriveFileSrv.GetSpaceInfo:input_type -> clouddrive.FileRequest
	13, // 21: clouddrive.CloudDriveFileSrv.CreateFile:input_type -> clouddrive.CreateFileRequest
	15, // 22: clouddrive.CloudDriveFileSrv.CloseFile:input_type -> clouddrive.CloseFileRequest
	18, // 23: clouddrive.CloudDriveFileSrv.WriteToFile:input_type -> clouddrive.WriteFileRequest
	6,  // 24: clouddrive.CloudDriveFileSrv.GetDownloadUrlPath:input_type -> clouddrive.GetDownloadUrlPathRequest
	3,  // 25: clouddrive.CloudDriveFileSrv.GetToken:output_type -> clouddrive.JWTToken
	9,  // 26: clouddrive.CloudDriveFileSrv.GetSubFiles:output_type -> clouddrive.SubFilesReply
	21, // 27: clouddrive.CloudDriveFileSrv.FindFileByPath:output_type -> clouddrive.CloudDriveFile
	12, // 28: clouddrive.CloudDriveFileSrv.CreateFolder:output_type -> clouddrive.CreateFolderResult
	5,  // 29: clouddrive.CloudDriveFileSrv.RenameFile:output_type -> clouddrive.FileOperationResult
	5,  // 30: clouddrive.CloudDriveFileSrv.MoveFile:output_type -> clouddrive.FileOperationResult
	5,  // 31: clouddrive.CloudDriveFileSrv.CopyFile:output_type -> clouddrive.FileOperationResult
	5,  // 32: clouddrive.CloudDriveFileSrv.DeleteFile:output_type -> clouddrive.FileOperationResult
	22, // 33: clouddrive.CloudDriveFileSrv.GetSpaceInfo:output_type -> clouddrive.SpaceInfo
	14, // 34: clouddrive.CloudDriveFileSrv.CreateFile:output_type -> clouddrive.CreateFileResult
	5,  // 35: clouddrive.CloudDriveFileSrv.CloseFile:output_type -> clouddrive.FileOperationResult
	19, // 36: clouddrive.CloudDriveFileSrv.WriteToFile:output_type -> clouddrive.WriteFileResult
	7,  // 37: clouddrive.CloudDriveFileSrv.GetDownloadUrlPath:output_type -> clouddrive.DownloadUrlPathInfo
	25, // [25:38] is the sub-list for method output_type
	12, // [12:25] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_clouddrive_proto_init() }
func file_clouddrive_proto_init() {
	if File_clouddrive_proto != nil {
		return
	}
	file_clouddrive_proto_msgTypes[0].OneofWrappers = []any{}
	file_clouddrive_proto_msgTypes[2].OneofWrappers = []any{}
	file_clouddrive_proto_msgTypes[5].OneofWrappers = []any{}
	file_clouddrive_proto_msgTypes[6].OneofWrappers = []any{}
	file_clouddrive_proto_msgTypes[14].OneofWrappers = []any{}
	file_clouddrive_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clouddrive_proto_rawDesc), len(file_clouddrive_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clouddrive_proto_goTypes,
		DependencyIndexes: file_clouddrive_proto_depIdxs,
		EnumInfos:         file_clouddrive_proto_enumTypes,
		MessageInfos:      file_clouddrive_proto_msgTypes,
	}.Build()
	File_clouddrive_proto = out.File
	file_clouddrive_proto_goTypes = nil
	file_clouddrive_proto_depIdxs = nil
}
